// Test generated by RoostGPT for test spotifyTest using AI Type Open AI and AI Model gpt-4

package com.csc301.profilemicroservice;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;

public class DbQueryStatus_DbQueryStatus_03cbc2162e_Test {

    private DbQueryStatus dbQueryStatus;
    private DbQueryExecResult dbQueryExecResult;

    @BeforeEach
    public void setup() {
        dbQueryExecResult = mock(DbQueryExecResult.class);
    }

    @Test
    public void testDbQueryStatus_WithValidMessageAndDbQueryExecResult() {
        String message = "Test Message";
        dbQueryStatus = new DbQueryStatus(message, dbQueryExecResult);
        assertEquals(message, dbQueryStatus.getMessage());
        assertEquals(dbQueryExecResult, dbQueryStatus.getDbQueryExecResult());
    }

    @Test
    public void testDbQueryStatus_WithNullMessageAndDbQueryExecResult() {
        String message = null;
        dbQueryStatus = new DbQueryStatus(message, dbQueryExecResult);
        assertEquals(message, dbQueryStatus.getMessage());
        assertEquals(dbQueryExecResult, dbQueryStatus.getDbQueryExecResult());
    }

    @Test
    public void testDbQueryStatus_WithValidMessageAndNullDbQueryExecResult() {
        String message = "Test Message";
        dbQueryExecResult = null;
        dbQueryStatus = new DbQueryStatus(message, dbQueryExecResult);
        assertEquals(message, dbQueryStatus.getMessage());
        assertEquals(dbQueryExecResult, dbQueryStatus.getDbQueryExecResult());
    }
}
